---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: opentelemetry
  namespace: monitoring
spec:
  interval: 10m0s
  provider: generic
  timeout: 1m0s
  url: https://open-telemetry.github.io/opentelemetry-helm-charts