
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana-tempo
resources:
- namespace.yaml
- release.yaml
- clusterrole.yaml
- deployment.yaml
- service.yaml
- tempo-patch.yaml


configMapGenerator:
- name: grafana-agent-traces

patches:
- path: agent/configmap.yaml